// Textos de la interfaz. Se elige el idioma del navegador; español por defecto.

(function (raiz) {
  'use strict';

  const es = {
    abrir: 'Abrir Flecha',
    sinProyectos: 'Aún no hay proyectos. Crea el primero.',
    nuevoProyecto: 'Nuevo proyecto',
    nombreProyecto: 'Nombre',
    finalizadas: 'Finalizadas',
    personalizar: 'Personalizar',
    atras: 'Atrás',
    nuevaTarea: 'Nueva tarea',
    completar: 'Marcar como finalizada',
    quitar: 'Quitar',
    ajustarAvance: 'Ajustar avance',
    listo: 'Listo',
    eliminarProyecto: 'Eliminar proyecto',
    confirmarEliminar: '¿Eliminar de verdad?',
    sinPendientes: 'Sin pendientes. Agrega la primera tarea.',
    nadaFinalizado: 'Aquí aparecerá lo que termines, por si quieres revertirlo.',
    revertir: 'Revertir',
    proyectoTerminado: 'Terminado',
    color: 'Color',
    colorAuto: 'Automático',
    colorMulti: 'Multicolor',
    colorPropio: 'Otro color',
    forma: 'Forma',
    formaRedondeada: 'Redondeada',
    formaPildora: 'Píldora',
    formaFina: 'Fina',
    lado: 'Lado',
    izquierda: 'Izquierda',
    derecha: 'Derecha',
    tema: 'Tema',
    temaAuto: 'Auto',
    claro: 'Claro',
    oscuro: 'Oscuro',
    datos: 'Datos',
    exportar: 'Exportar',
    importar: 'Importar',
    empezarDeCero: 'Empezar de cero',
    notaLocal: 'Tus datos viven solo en este navegador. Exporta un respaldo de vez en cuando.',
    notaServidor: 'Tus datos viven en flecha.json y finalizadas.json, en tu computadora.',
    notaEjemplo: 'Estás viendo proyectos de ejemplo.',
    avisoTarea: 'Tarea finalizada',
    avisoProyecto: 'Proyecto terminado',
    avisoEliminado: 'Proyecto eliminado',
    avisoRevertida: 'De vuelta en pendientes',
    avisoExterno: 'Actualizado desde el archivo',
    avisoImportado: 'Datos importados',
    avisoImportMal: 'Ese archivo no es de Flecha',
    avisoNoGuardo: 'No se pudo guardar',
    deshacer: 'Deshacer',
    vence: 'vence',
    fechaLimite: 'Fecha límite',
    descanso: 'hoy descansa',
    racha: 'racha',
    dias: 'días',
    uso: 'Uso',
    ventana5h: '5 h',
    ventana7d: 'semana',
    ventanaGasto: 'gasto',
    reinicia: 'reinicia en',
    sinUso: 'sin uso',
    hoy: 'hoy',
    sieteDias: '7 días',
    conectarClaude: 'Para ver los límites de Claude, corre una vez: ./flecha --conectar-claude',
  };

  const en = {
    abrir: 'Open Flecha',
    sinProyectos: 'No projects yet. Create the first one.',
    nuevoProyecto: 'New project',
    nombreProyecto: 'Name',
    finalizadas: 'Completed',
    personalizar: 'Customize',
    atras: 'Back',
    nuevaTarea: 'New task',
    completar: 'Mark as completed',
    quitar: 'Remove',
    ajustarAvance: 'Adjust progress',
    listo: 'Done',
    eliminarProyecto: 'Delete project',
    confirmarEliminar: 'Really delete?',
    sinPendientes: 'Nothing pending. Add the first task.',
    nadaFinalizado: 'What you finish shows up here, in case you want to revert it.',
    revertir: 'Revert',
    proyectoTerminado: 'Finished',
    color: 'Color',
    colorAuto: 'Automatic',
    colorMulti: 'Multicolor',
    colorPropio: 'Other color',
    forma: 'Shape',
    formaRedondeada: 'Rounded',
    formaPildora: 'Pill',
    formaFina: 'Thin',
    lado: 'Side',
    izquierda: 'Left',
    derecha: 'Right',
    tema: 'Theme',
    temaAuto: 'Auto',
    claro: 'Light',
    oscuro: 'Dark',
    datos: 'Data',
    exportar: 'Export',
    importar: 'Import',
    empezarDeCero: 'Start from scratch',
    notaLocal: 'Your data lives only in this browser. Export a backup now and then.',
    notaServidor: 'Your data lives in flecha.json and finalizadas.json, on your computer.',
    notaEjemplo: 'You are looking at sample projects.',
    avisoTarea: 'Task completed',
    avisoProyecto: 'Project finished',
    avisoEliminado: 'Project deleted',
    avisoRevertida: 'Back in pending',
    avisoExterno: 'Updated from the file',
    avisoImportado: 'Data imported',
    avisoImportMal: 'That file is not from Flecha',
    avisoNoGuardo: 'Could not save',
    deshacer: 'Undo',
    vence: 'due',
    fechaLimite: 'Due date',
    descanso: 'rest day',
    racha: 'streak',
    dias: 'days',
    uso: 'Usage',
    ventana5h: '5 h',
    ventana7d: 'week',
    ventanaGasto: 'spend',
    reinicia: 'resets in',
    sinUso: 'unused',
    hoy: 'today',
    sieteDias: '7 days',
    conectarClaude: 'To see Claude limits, run once: ./flecha --conectar-claude',
  };

  const idioma = ((raiz.navigator && raiz.navigator.language) || 'es').toLowerCase().startsWith('en') ? 'en' : 'es';
  const tabla = idioma === 'en' ? en : es;

  raiz.Flecha = Object.assign(raiz.Flecha || {}, {
    idioma,
    t: (clave) => tabla[clave] || es[clave] || clave,
  });
})(typeof globalThis !== 'undefined' ? globalThis : this);
